# These are supported funding model platforms

github: [MatthewRobertLotts]
# patreon: # Replace with your Patreon
# ko_fi: # Replace with your Ko-fi
# buy_me_a_coffee: # Replace with Buy me a coffee
# custom: ['https://saveroom.co.uk']
